# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa22fa55da0726f11b961aad697256c8eb76d3a1851f291628dcbc2d9196cdd3edce0cb69b353b5fb70627149c7b051d56fc9cfbc06b2e3dbee63a46221ccc89

test:
  secret_key_base: dc835462ebeeb1a89119df51649d4bb27ffd352f8e56c400675bf6da7c2e424d4c850b3a539076f4acb0c82f7971132815d3279525c9830b19e2432732f6c9e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
